spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}/batch
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

kafka:
  producer:
    bootstrap-servers: ${KAFKA_URL}:9092
    key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    value-serializer: com.picky.notificationproducer.config.CustomSerializer

server:
  port: 8082
